#!/bin/bash -e

# run core
bash <(curl -fsSL https://mesg.com/install)

# run envoy
# only ExecuteTask and ListenResult APIs exposed
docker build -t envoy:core -f Dockerfile.envoy .
docker service create --name core-envoy --network core -p 50053:50053 envoy:core

# run marketplace service
cd /tmp
git clone https://github.com/mesg-foundation/core
cd core
git fetch origin ss/martketplace-local-data
git checkout ss/martketplace-local-data
cd systemservices/marketplace
mesg-core service deploy
mesg-core service start marketplace

# disallow connecting to core from internet
# TODO use ufw instead
docker service update core --publish-rm 50052